/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDDC;

import com.mysql.jdbc.Connection;
import java.awt.TextField;
import javax.swing.JOptionPane;

/**
 *
 * @author dedei
 */
public class Inserts extends javax.swing.JFrame {
    private String tabla;
    private String[] datos;
    private Acceso_BDD con;
    /**
     * Creates new form Inserts
     */
    public Inserts(String t, Acceso_BDD con) {
        initComponents();
        tabla=t;
        this.con=con;
        if(tabla.equalsIgnoreCase("Correos")){
            uno.setText("ID Contacto: ");
            dos.setText("Correo: ");
        }
        if(tabla.equalsIgnoreCase("Telefonos")){
            uno.setText("ID Contacto: ");
            dos.setText("Telefono: ");
        }
    }

    private Inserts() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uno = new javax.swing.JLabel();
        cajaUno = new javax.swing.JTextField();
        dos = new javax.swing.JLabel();
        CajaDos = new javax.swing.JTextField();
        insertar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uno.setText("Nombre:");

        dos.setText("Ciudad: ");

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dos)
                            .addComponent(uno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(insertar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CajaDos, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(cajaUno)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uno)
                    .addComponent(cajaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dos)
                    .addComponent(CajaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertar)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        if(cajaUno.getText().length()==0 || CajaDos.getText().length()==0)
            JOptionPane.showMessageDialog(null, "No deje datos vacios", "Error",JOptionPane.INFORMATION_MESSAGE);
        else
        {
            
        if (tabla.equalsIgnoreCase("Contactos")) {
            con.insertarContactos(cajaUno.getText(),CajaDos.getText());
        }

        if (tabla.equalsIgnoreCase("Correos")) {
            int uno = Integer.parseInt(this.cajaUno.getText());
            if (!con.insertarCorreos(uno, CajaDos.getText())) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese al contacto en la Base de Datos primero", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        if (tabla.equalsIgnoreCase("Telefonos")) {
            int uno = Integer.parseInt(this.cajaUno.getText());
            if (!con.insertarTelefonos(uno, CajaDos.getText())) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese al contacto en la Base de Datos primero", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
            
            dispose();
        }
    }//GEN-LAST:event_insertarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    public Acceso_BDD getCon() {
        return con;
    }
    
    @SuppressWarnings("empty-statement")
    public String[] enviarString(){
        
        return datos;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaDos;
    private javax.swing.JTextField cajaUno;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel dos;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel uno;
    // End of variables declaration//GEN-END:variables
}
